# Generated by Django 4.2.21 on 2025-05-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="friend",
            name="accepted",
        ),
        migrations.AddField(
            model_name="friend",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="friend",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
