# Generated by Django 4.2.21 on 2025-05-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_remove_friend_accepted_friend_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="type",
            field=models.CharField(
                choices=[
                    ("distance", "Distance"),
                    ("duration", "Duration"),
                    ("count", "Run Count"),
                ],
                default="distance",
                max_length=10,
            ),
        ),
    ]
