# Generated by Django 4.2.21 on 2025-05-22 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_challenge_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activityitem",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RenameField(
            model_name="activityitem",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="activityitem",
            name="friend_relationship",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.friend",
            ),
        ),
        migrations.AddField(
            model_name="activityitem",
            name="run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.run",
            ),
        ),
        migrations.AddField(
            model_name="activityitem",
            name="user_achievement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.userachievement",
            ),
        ),
        migrations.AddField(
            model_name="activityitem",
            name="user_challenge",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.userchallenge",
            ),
        ),
    ]
