# Generated by Django 4.2.21 on 2025-05-22 16:18

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_activityitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userraceattempt",
            name="actual_route_data",
            field=django.contrib.gis.db.models.fields.LineStringField(
                blank=True, geography=True, null=True, srid=4326
            ),
        ),
    ]
