# Generated by Django 4.2.21 on 2025-05-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_userraceattempt_actual_route_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="userraceattempt",
            name="actual_distance_meters",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
