# Generated by Django 4.2.21 on 2025-05-25 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_userraceattempt_actual_distance_meters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="challenge",
            name="type",
        ),
        migrations.AddField(
            model_name="achievement",
            name="achievement_type",
            field=models.CharField(
                choices=[
                    ("distance", "Distance"),
                    ("duration", "Duration"),
                    ("run_count", "Run Count"),
                    ("race_count", "Race Count"),
                    ("specific_route", "Specific Route"),
                ],
                default="run_count",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="achievement",
            name="target_value",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="achievement",
            name="unit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="challenge_type",
            field=models.CharField(
                choices=[
                    ("distance_goal", "Distance Goal"),
                    ("duration_goal", "Duration Goal"),
                    ("run_count_goal", "Run Count Goal"),
                    ("complete_racetrack", "Complete Racetrack"),
                ],
                default="distance_goal",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="is_competitive",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="challenge",
            name="related_racetrack",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.racetrack",
            ),
        ),
        migrations.AddField(
            model_name="challenge",
            name="start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="challenge",
            name="unit",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="racetrack",
            name="length_meters",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userachievement",
            name="completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userachievement",
            name="completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userchallenge",
            name="completion_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="achievement",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="challenge",
            name="target_value",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
