# Generated by Django 4.2.21 on 2025-05-25 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_remove_challenge_type_achievement_achievement_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityitem",
            name="user_race_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.userraceattempt",
            ),
        ),
    ]
