# Generated by Django 4.2.21 on 2025-05-26 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_activityitem_user_race_attempt"),
    ]

    operations = [
        migrations.AddField(
            model_name="racetrack",
            name="base_xp_reward",
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name="racetrack",
            name="route_match_xp_multiplier",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="racetrack",
            name="xp_penalty_per_second",
            field=models.FloatField(default=2.0),
        ),
    ]
