# Generated by Django 4.2.21 on 2025-05-26 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_racetrack_base_xp_reward_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityitem",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
    ]
