# Generated by Django 4.2.21 on 2025-05-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_jointruninvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="jointruninvitation",
            name="meeting_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
