# Generated by Django 4.2.21 on 2025-05-26 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0013_jointruninvitation_meeting_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedJointRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("suggested_time", models.DateTimeField(blank=True, null=True)),
                (
                    "meeting_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "invitation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planned_run",
                        to="core.jointruninvitation",
                    ),
                ),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="planned_joint_runs", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "suggested_racetrack",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.racetrack",
                    ),
                ),
            ],
        ),
    ]
