# Generated by Django 4.2.21 on 2025-05-26 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_activitycomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityitem",
            name="allow_comments",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="activityitem",
            name="planned_joint_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.plannedjointrun",
            ),
        ),
    ]
