# Generated by Django 4.2.21 on 2025-05-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_activityitem_allow_comments_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_achievements",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_challenges",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="show_runs",
            field=models.BooleanField(default=True),
        ),
    ]
