# Generated by Django 4.2.21 on 2025-05-26 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0018_profile_is_public_profile_show_achievements_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityitem",
            name="related_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_activity_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
