# Generated by Django 4.2.21 on 2025-05-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_activityitem_related_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="show_statistics",
            field=models.BooleanField(default=True),
        ),
    ]
