# Generated by Django 4.2.21 on 2025-05-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_profile_show_statistics"),
    ]

    operations = [
        migrations.AddField(
            model_name="plannedjointrun",
            name="actual_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
