# Generated by Django 4.2.21 on 2025-05-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_devicetoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="racetrack",
            name="distance_meters",
        ),
    ]
