# Generated by Django 4.2.21 on 2025-05-29 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_remove_racetrack_distance_meters"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="is_secret",
            field=models.BooleanField(
                default=False, verbose_name="Секретное достижение"
            ),
        ),
    ]
