# Generated by Django 4.2.21 on 2025-06-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_achievement_is_secret"),
    ]

    operations = [
        migrations.AddField(
            model_name="userraceattempt",
            name="completion_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userraceattempt",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
