# Generated by Django 4.2.21 on 2025-06-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_userraceattempt_completion_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="run",
            name="completed_challenges",
            field=models.ManyToManyField(
                blank=True, related_name="runs_completed_in", to="core.challenge"
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="earned_achievements",
            field=models.ManyToManyField(
                blank=True, related_name="runs_earned_in", to="core.achievement"
            ),
        ),
        migrations.AddField(
            model_name="run",
            name="xp_earned",
            field=models.IntegerField(default=0),
        ),
    ]
