# Generated by Django 4.2.21 on 2025-06-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_run_completed_challenges_run_earned_achievements_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userraceattempt",
            name="completed_challenges",
            field=models.ManyToManyField(
                blank=True,
                related_name="race_attempts_completed_in",
                to="core.challenge",
            ),
        ),
        migrations.AddField(
            model_name="userraceattempt",
            name="earned_achievements",
            field=models.ManyToManyField(
                blank=True,
                related_name="race_attempts_earned_in",
                to="core.achievement",
            ),
        ),
    ]
