# Generated by Django 4.2.21 on 2025-06-13 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_userraceattempt_completed_challenges_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="activityitem",
            name="joint_run_invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activity_items",
                to="core.jointruninvitation",
            ),
        ),
    ]
