# Generated by Django 4.2.21 on 2025-06-19 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_suggestedroute"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="suggestedroute",
            name="link",
        ),
    ]
